-- DEPRECATED: hourly Supabase Cron + Edge Function sync (Bargo).
-- Congressional trade updates are now performed manually with:
--   cd backend && npm run update-data
-- or by double-clicking update.bat on Windows.
-- Do not apply this cron job for new deployments.
