#!/usr/bin/env bash
# Create local Postgres roles/DB, apply schema, write env files, seed demo rows.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

bash "$ROOT/scripts/local-db/install-postgrest.sh"

if ! command -v psql >/dev/null; then
  echo "psql not found. Install postgresql + postgresql-contrib first."
  exit 1
fi

# Start cluster if present (Ubuntu packages)
if command -v pg_ctlcluster >/dev/null; then
  sudo pg_ctlcluster 16 main start 2>/dev/null || true
fi

echo "==> Creating roles and database"
sudo -u postgres psql <<'SQL'
DO $$ BEGIN CREATE ROLE anon NOLOGIN NOINHERIT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE authenticated NOLOGIN NOINHERIT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE service_role NOLOGIN NOINHERIT BYPASSRLS; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'localdev';
EXCEPTION WHEN duplicate_object THEN
  ALTER ROLE authenticator WITH LOGIN PASSWORD 'localdev' NOINHERIT;
END $$;
GRANT anon TO authenticator;
GRANT authenticated TO authenticator;
GRANT service_role TO authenticator;
DO $$ BEGIN
  CREATE ROLE postgres SUPERUSER LOGIN PASSWORD 'localdev';
EXCEPTION WHEN duplicate_object THEN
  ALTER ROLE postgres WITH LOGIN PASSWORD 'localdev';
END $$;
SELECT 'ok' WHERE EXISTS (SELECT 1 FROM pg_database WHERE datname = 'hedgpix');
SQL

if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='hedgpix'" | grep -q 1; then
  sudo -u postgres createdb hedgpix
fi

sudo -u postgres psql -d hedgpix <<'SQL'
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
CREATE OR REPLACE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('request.jwt.claim.role', true), '')::text;
$$;
CREATE TABLE IF NOT EXISTS auth.users (
  id uuid PRIMARY KEY,
  email text,
  raw_user_meta_data jsonb,
  created_at timestamptz DEFAULT now()
);
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role, authenticator;
GRANT USAGE ON SCHEMA auth TO anon, authenticated, service_role;
GRANT SELECT ON auth.users TO anon, authenticated, service_role;
SQL

echo "==> Applying schema"
bash "$ROOT/scripts/local-db/migrate.sh"

echo "==> Writing PostgREST config + env files"
mkdir -p "$ROOT/local-db"
eval "$(python3 "$ROOT/scripts/local-db/mint-keys.py" | sed 's/^/export /')"

cat > "$ROOT/local-db/postgrest.conf" <<EOF
db-uri = "postgres://authenticator:localdev@127.0.0.1:5432/hedgpix"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "${JWT_SECRET}"
server-port = 54322
server-host = "127.0.0.1"
EOF

cat > "$ROOT/local-db/keys.env" <<EOF
# Generated by scripts/local-db/bootstrap.sh — local development only
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
SUPABASE_URL=${SUPABASE_URL}
DATABASE_URL=${DATABASE_URL}
JWT_SECRET=${JWT_SECRET}
EOF

# Preserve Alpaca keys if already set
preserve_alpaca() {
  local file="$1"
  local key="" secret=""
  if [[ -f "$file" ]]; then
    key="$(grep -E '^ALPACA_API_KEY=' "$file" | tail -1 || true)"
    secret="$(grep -E '^ALPACA_API_SECRET=' "$file" | tail -1 || true)"
  fi
  cat > "$file" <<EOF
# Local PostgREST (generated by npm run local:db:bootstrap)
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
SUPABASE_URL=${SUPABASE_URL}
DATABASE_URL=${DATABASE_URL}
${key:-# ALPACA_API_KEY=}
${secret:-# ALPACA_API_SECRET=}
EOF
}

preserve_alpaca "$ROOT/.env.local"
preserve_backend() {
  local file="$ROOT/backend/.env"
  local extra=""
  if [[ -f "$file" ]]; then
    extra="$(grep -E '^(ALPACA_|INSIDERWATCH_|INITIAL_|SYNC_|KADOA_)' "$file" || true)"
  fi
  cat > "$file" <<EOF
# Local PostgREST (generated by npm run local:db:bootstrap)
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DATABASE_URL=${DATABASE_URL}
${extra}
EOF
}
preserve_backend

echo "==> Seeding demo rows"
sudo -u postgres psql -d hedgpix -f "$ROOT/scripts/local-db/seed-demo.sql"

echo
echo "Bootstrap complete."
echo "  Start API:  npm run local:db:start"
echo "  Frontend:   npm run dev"
echo "  Env files:  .env.local and backend/.env now point at http://127.0.0.1:54321"
